import { createListSlice } from "./createListSlice";

// Mock leads covering every enquiry channel from the spec (Call, Chat, Callback Request, Contact
// Form, WhatsApp), every stage of the funnel (New -> Contacted -> Follow-up -> Interested ->
// Site Visit -> Negotiation -> Converted/Lost), and a couple of obvious-spam entries so the
// genuine/spam flagging toggle (Section 4.4) has something real to demonstrate.
const initialItems = [
  {
    id: "LED-30001",
    listingId: "PRP-10234",
    listingTitle: "Spacious 2BHK Apartment in Prestige Tower 1",
    buyerName: "Ananya Roy",
    buyerPhone: "+91 98111 22334",
    buyerEmail: "ananya.roy@example.com",
    channel: "Call",
    message: "Interested in this 2BHK — is home loan assistance available through the platform?",
    budget: "₹70L - ₹85L",
    status: "new",
    flag: "unreviewed",
    assignedTo: "agent_ravi",
    createdDate: "2026-09-20",
    lastActivity: "2026-09-20",
  },
  {
    id: "LED-30002",
    listingId: "PRP-10891",
    listingTitle: "Palm Meadows 4BHK Villa",
    buyerName: "Karan Malhotra",
    buyerPhone: "+91 98220 44556",
    buyerEmail: "karan.malhotra@example.com",
    channel: "Chat",
    message: "Can I schedule a site visit this weekend? Saturday afternoon works best for me.",
    budget: "₹3 Cr - ₹3.5 Cr",
    status: "site_visit",
    flag: "genuine",
    assignedTo: "agent_ravi",
    createdDate: "2026-09-19",
    lastActivity: "2026-09-20",
  },
  {
    id: "LED-30003",
    listingId: "PRP-11207",
    listingTitle: "Residential Plot, Sector 88",
    buyerName: "Suresh Iyer",
    buyerPhone: "+91 99887 11223",
    buyerEmail: "suresh.iyer@example.com",
    channel: "Callback Request",
    message: "Please call me back regarding pricing negotiation — flexible on timeline.",
    budget: "₹85L - ₹1Cr",
    status: "negotiation",
    flag: "genuine",
    assignedTo: "dealer_shah",
    createdDate: "2026-09-18",
    lastActivity: "2026-09-19",
  },
  {
    id: "LED-30004",
    listingId: "PRP-11540",
    listingTitle: "Office Space, Cyber Hub",
    buyerName: "Meena Kapoor",
    buyerPhone: "+91 90210 55667",
    buyerEmail: "meena.kapoor@example.com",
    channel: "Contact Form",
    message: "Looking for immediate lease for a 20-seat startup office — please share availability.",
    budget: "₹2L - ₹2.5L/mo",
    status: "converted",
    flag: "genuine",
    assignedTo: "builder_cyberhub",
    createdDate: "2026-09-10",
    lastActivity: "2026-09-16",
  },
  {
    id: "LED-30005",
    listingId: "PRP-11902",
    listingTitle: "Zenith PG for Boys",
    buyerName: "Rohit Sharma",
    buyerPhone: "+91 88990 33445",
    buyerEmail: "rohit.sharma@example.com",
    channel: "WhatsApp",
    message: "Is the PG strictly boys-only? What's included in the rent — meals, wifi?",
    budget: "₹12K - ₹15K/mo",
    status: "new",
    flag: "unreviewed",
    assignedTo: "owner_zenith",
    createdDate: "2026-09-21",
    lastActivity: "2026-09-21",
  },
  {
    id: "LED-30006",
    listingId: "PRP-12034",
    listingTitle: "1BHK Flat, Kharadi",
    buyerName: "Congratulations Winner",
    buyerPhone: "+91 00000 00000",
    buyerEmail: "claim-prize@totally-not-spam.example.com",
    channel: "Call",
    message: "Congratulations!! You've won a free consultation, call this number now to claim!!!",
    budget: "₹20K/mo",
    status: "lost",
    flag: "spam",
    assignedTo: "owner_priya",
    createdDate: "2026-09-05",
    lastActivity: "2026-09-05",
  },
  {
    id: "LED-30007",
    listingId: "PRP-12156",
    listingTitle: "3BHK Villa in Sarjapur",
    buyerName: "Divya Nair",
    buyerPhone: "+91 97700 88112",
    buyerEmail: "divya.nair@example.com",
    channel: "Chat",
    message: "What's the final negotiable price? Also is the sale deed clear of litigation?",
    budget: "₹1.8Cr - ₹2.2Cr",
    status: "negotiation",
    flag: "genuine",
    assignedTo: "agent_ravi",
    createdDate: "2026-09-15",
    lastActivity: "2026-09-17",
  },
  {
    id: "LED-30008",
    listingId: "PRP-12280",
    listingTitle: "Sector 62 IT Park Office Floor",
    buyerName: "Aditya Verma",
    buyerPhone: "+91 96650 22114",
    buyerEmail: "aditya.verma@example.com",
    channel: "Contact Form",
    message: "Need this space for a startup office, around 20 seats. Can we discuss lease terms?",
    budget: "₹3.5Cr - ₹4.5Cr",
    status: "new",
    flag: "unreviewed",
    assignedTo: "builder_cyberhub",
    createdDate: "2026-09-20",
    lastActivity: "2026-09-20",
  },
  {
    id: "LED-30009",
    listingId: "PRP-12390",
    listingTitle: "Green Acres Farm Plot",
    buyerName: "Quick Loan Offers",
    buyerPhone: "+91 11111 11111",
    buyerEmail: "offers@bulk-mailer.example.com",
    channel: "Callback Request",
    message: "Click here for instant loan approval no matter your credit score, limited time only.",
    budget: "₹1.5Cr",
    status: "lost",
    flag: "spam",
    assignedTo: "dealer_shah",
    createdDate: "2026-09-01",
    lastActivity: "2026-09-01",
  },
  {
    id: "LED-30010",
    listingId: "PRP-12455",
    listingTitle: "Co-ed PG near Hitech City",
    buyerName: "Farhan Sheikh",
    buyerPhone: "+91 95050 66778",
    buyerEmail: "farhan.sheikh@example.com",
    channel: "WhatsApp",
    message: "Any single-sharing rooms available? What's the move-in date look like?",
    budget: "₹10K - ₹12K/mo",
    status: "interested",
    flag: "genuine",
    assignedTo: "owner_meridian",
    createdDate: "2026-09-19",
    lastActivity: "2026-09-20",
  },
  {
    id: "LED-30011",
    listingId: "PRP-12510",
    listingTitle: "Skyline Residency 3BHK",
    buyerName: "Sneha Joshi",
    buyerPhone: "+91 93330 99887",
    buyerEmail: "sneha.joshi@example.com",
    channel: "Call",
    message: "Can you send more photos of the interiors and the clubhouse amenities?",
    budget: "₹2.2Cr - ₹2.5Cr",
    status: "new",
    flag: "unreviewed",
    assignedTo: "agent_desai",
    createdDate: "2026-09-21",
    lastActivity: "2026-09-21",
  },
  {
    id: "LED-30012",
    listingId: "PRP-12588",
    listingTitle: "Baner Heights Studio",
    buyerName: "Vivek Rao",
    buyerPhone: "+91 90900 11223",
    buyerEmail: "vivek.rao@example.com",
    channel: "Chat",
    message: "Is this still available? I want to move in immediately, ready to sign this week.",
    budget: "₹15K - ₹18K/mo",
    status: "converted",
    flag: "genuine",
    assignedTo: "owner_kulkarni",
    createdDate: "2026-09-03",
    lastActivity: "2026-09-08",
  },
  {
    id: "LED-30013",
    listingId: "PRP-10234",
    listingTitle: "Spacious 2BHK Apartment in Prestige Tower 1",
    buyerName: "Priyanka Das",
    buyerPhone: "+91 98765 22110",
    buyerEmail: "priyanka.das@example.com",
    channel: "Contact Form",
    message: "What's the monthly maintenance charge, and is it inclusive of the clubhouse fee?",
    budget: "₹75L - ₹85L",
    status: "contacted",
    flag: "genuine",
    assignedTo: "agent_ravi",
    createdDate: "2026-09-17",
    lastActivity: "2026-09-18",
  },
  {
    id: "LED-30014",
    listingId: "PRP-11540",
    listingTitle: "Office Space, Cyber Hub",
    buyerName: "Prize Notification",
    buyerPhone: "+91 22222 22222",
    buyerEmail: "urgent-claim@click-here.example.com",
    channel: "WhatsApp",
    message: "URGENT!!! Click this link immediately to claim your prize before it expires today!",
    budget: "₹2L/mo",
    status: "new",
    flag: "unreviewed",
    assignedTo: "builder_cyberhub",
    createdDate: "2026-09-21",
    lastActivity: "2026-09-21",
  },
];

const leadsSlice = createListSlice("leads", {
  items: initialItems,
  filters: { channel: "all", status: "all", flag: "all" },
});

export const {
  setItems: setLeads,
  setFilters: setLeadsFilters,
  resetFilters: resetLeadsFilters,
  setSelectedId: setSelectedLeadId,
  setLoading: setLeadsLoading,
  setError: setLeadsError,
  addItem: addLead,
  updateItem: updateLead,
  removeItem: removeLead,
  removeItems: removeLeads,
  updateItemStatus: updateLeadStatus,
  updateItemsStatus: updateLeadsStatus,
} = leadsSlice.actions;

export default leadsSlice.reducer;
