import { createListSlice } from "./createListSlice";

// Mock reviews mixing genuine feedback with a couple of obvious abusive/fake entries so the
// approve/reject/flag moderation flow (Section 4.7) has something real to demonstrate.
const initialItems = [
  {
    id: "REV-40001",
    listingId: "PRP-10234",
    listingTitle: "Spacious 2BHK Apartment in Prestige Tower 1",
    reviewerName: "Ritu Sharma",
    reviewerEmail: "ritu.sharma@example.com",
    rating: 5,
    title: "Great experience!",
    comment: "The agent was very responsive and the flat matches the photos exactly.",
    status: "pending",
    submittedDate: "2026-09-20",
  },
  {
    id: "REV-40002",
    listingId: "PRP-10891",
    listingTitle: "Palm Meadows 4BHK Villa",
    reviewerName: "Manoj Tiwari",
    reviewerEmail: "manoj.tiwari@example.com",
    rating: 4,
    title: "Beautiful villa",
    comment: "Spacious and well maintained, minor issue with garden upkeep.",
    status: "approved",
    submittedDate: "2026-09-15",
  },
  {
    id: "REV-40003",
    listingId: "PRP-11540",
    listingTitle: "Office Space, Cyber Hub",
    reviewerName: "Anita Desai",
    reviewerEmail: "anita.desai@example.com",
    rating: 1,
    title: "Scam listing!!!",
    comment: "This is a FAKE listing, they took my booking amount and vanished. Read my full story at totally-legit-blog.example",
    status: "flagged",
    moderationReason: "Contains an external link and an unverified fraud accusation — needs investigation before publishing.",
    submittedDate: "2026-09-10",
  },
  {
    id: "REV-40004",
    listingId: "PRP-11902",
    listingTitle: "Zenith PG for Boys",
    reviewerName: "Karthik Reddy",
    reviewerEmail: "karthik.reddy@example.com",
    rating: 3,
    title: "Decent PG",
    comment: "Food quality could be better but the rooms are clean.",
    status: "approved",
    submittedDate: "2026-09-08",
  },
  {
    id: "REV-40005",
    listingId: "PRP-12034",
    listingTitle: "1BHK Flat, Kharadi",
    reviewerName: "dealz4u_promo",
    reviewerEmail: "promo@bulk-mailer.example.com",
    rating: 5,
    title: "asdkjasjd",
    comment: "Visit spammy-site.example for cheap real estate deals!!! Limited time offer!!!",
    status: "flagged",
    moderationReason: "Spam content unrelated to the property.",
    submittedDate: "2026-09-05",
  },
  {
    id: "REV-40006",
    listingId: "PRP-12156",
    listingTitle: "3BHK Villa in Sarjapur",
    reviewerName: "Sunita Rao",
    reviewerEmail: "sunita.rao@example.com",
    rating: 2,
    title: "Disappointed",
    comment: "The villa had water leakage issues that weren't disclosed by the seller.",
    status: "pending",
    submittedDate: "2026-09-19",
  },
  {
    id: "REV-40007",
    listingId: "PRP-12280",
    listingTitle: "Sector 62 IT Park Office Floor",
    reviewerName: "Rajesh Mehta",
    reviewerEmail: "rajesh.mehta@example.com",
    rating: 5,
    title: "Perfect office space",
    comment: "Everything as described, smooth transaction with the builder.",
    status: "approved",
    submittedDate: "2026-09-02",
  },
  {
    id: "REV-40008",
    listingId: "PRP-12390",
    listingTitle: "Green Acres Farm Plot",
    reviewerName: "anonymous_user_88",
    reviewerEmail: "anon88@example.com",
    rating: 1,
    title: "Stay away from this seller",
    comment: "Extremely rude and unprofessional — used abusive language when I asked basic questions about the plot boundary.",
    status: "flagged",
    moderationReason: "Reviewer's own language when describing the exchange includes profanity — held for manual review.",
    submittedDate: "2026-08-28",
  },
  {
    id: "REV-40009",
    listingId: "PRP-12455",
    listingTitle: "Co-ed PG near Hitech City",
    reviewerName: "Divya Nair",
    reviewerEmail: "divya.nair@example.com",
    rating: 4,
    title: "Good value",
    comment: "Clean and affordable, would recommend it to students.",
    status: "pending",
    submittedDate: "2026-09-19",
  },
  {
    id: "REV-40010",
    listingId: "PRP-10234",
    listingTitle: "Spacious 2BHK Apartment in Prestige Tower 1",
    reviewerName: "Amit Kumar",
    reviewerEmail: "amit.kumar@example.com",
    rating: 2,
    title: "Overpriced",
    comment: "Nice flat but the price doesn't match the market rate for the area.",
    status: "rejected",
    moderationReason: "Duplicate review — the same content was posted twice by this user.",
    submittedDate: "2026-09-01",
  },
];

const reviewsSlice = createListSlice("reviews", {
  items: initialItems,
  filters: { status: "all", rating: "all" },
});

export const {
  setItems: setReviews,
  setFilters: setReviewsFilters,
  resetFilters: resetReviewsFilters,
  setSelectedId: setSelectedReviewId,
  setLoading: setReviewsLoading,
  setError: setReviewsError,
  addItem: addReview,
  updateItem: updateReview,
  removeItem: removeReview,
  removeItems: removeReviews,
  updateItemStatus: updateReviewStatus,
  updateItemsStatus: updateReviewsStatus,
} = reviewsSlice.actions;

export default reviewsSlice.reducer;
