import { createListSlice } from "./createListSlice";

// Mock saved searches — buyers/tenants who've set up alert criteria on the public site. Cities
// and property types match the vocabulary already used in Listings/Leads so filtering feels
// connected to the rest of the platform rather than inventing a new taxonomy.
const initialItems = [
  {
    id: "SS-50001",
    userName: "Sunita Kulkarni",
    userEmail: "sunita.kulkarni@example.com",
    city: "Pune",
    propertyType: "Apartment",
    listingType: "Sell",
    minBudget: 6000000,
    maxBudget: 9000000,
    bedrooms: "2+",
    alertFrequency: "Instant",
    matchesCount: 14,
    status: "active",
    createdDate: "2026-08-12",
    lastAlertSent: "2026-09-21",
  },
  {
    id: "SS-50002",
    userName: "Rajesh Kumar",
    userEmail: "rajesh.kumar@example.com",
    city: "Noida",
    propertyType: "Villa",
    listingType: "Sell",
    minBudget: 15000000,
    maxBudget: 25000000,
    bedrooms: "4+",
    alertFrequency: "Daily",
    matchesCount: 3,
    status: "active",
    createdDate: "2026-07-30",
    lastAlertSent: "2026-09-20",
  },
  {
    id: "SS-50003",
    userName: "Neha Kapoor",
    userEmail: "neha.kapoor@example.com",
    city: "Pune",
    propertyType: "Studio",
    listingType: "Rent",
    minBudget: 15000,
    maxBudget: 25000,
    bedrooms: "1",
    alertFrequency: "Weekly",
    matchesCount: 9,
    status: "active",
    createdDate: "2026-06-18",
    lastAlertSent: "2026-09-15",
  },
  {
    id: "SS-50004",
    userName: "Farhan Sheikh",
    userEmail: "farhan.sheikh@example.com",
    city: "Hyderabad",
    propertyType: "PG",
    listingType: "PG",
    minBudget: 6000,
    maxBudget: 12000,
    bedrooms: "Any",
    alertFrequency: "Instant",
    matchesCount: 21,
    status: "active",
    createdDate: "2026-09-05",
    lastAlertSent: "2026-09-21",
  },
  {
    id: "SS-50005",
    userName: "Aditya Verma",
    userEmail: "aditya.verma@example.com",
    city: "Gurugram",
    propertyType: "Commercial",
    listingType: "Rent",
    minBudget: 200000,
    maxBudget: 400000,
    bedrooms: "Any",
    alertFrequency: "Daily",
    matchesCount: 2,
    status: "paused",
    createdDate: "2026-05-22",
    lastAlertSent: "2026-08-30",
  },
  {
    id: "SS-50006",
    userName: "Divya Nair",
    userEmail: "divya.nair@example.com",
    city: "Bengaluru",
    propertyType: "Villa",
    listingType: "Sell",
    minBudget: 12000000,
    maxBudget: 20000000,
    bedrooms: "3+",
    alertFrequency: "Weekly",
    matchesCount: 6,
    status: "active",
    createdDate: "2026-08-01",
    lastAlertSent: "2026-09-14",
  },
  {
    id: "SS-50007",
    userName: "Priyanka Das",
    userEmail: "priyanka.das@example.com",
    city: "Bengaluru",
    propertyType: "Apartment",
    listingType: "Rent",
    minBudget: 25000,
    maxBudget: 40000,
    bedrooms: "2",
    alertFrequency: "Off",
    matchesCount: 0,
    status: "paused",
    createdDate: "2026-04-11",
    lastAlertSent: "2026-06-02",
  },
];

const savedSearchesSlice = createListSlice("savedSearches", {
  items: initialItems,
  filters: { status: "all", city: "all" },
});

export const {
  setItems: setSavedSearches,
  setFilters: setSavedSearchesFilters,
  resetFilters: resetSavedSearchesFilters,
  setSelectedId: setSelectedSavedSearchId,
  setLoading: setSavedSearchesLoading,
  setError: setSavedSearchesError,
  addItem: addSavedSearch,
  updateItem: updateSavedSearch,
  removeItem: removeSavedSearch,
  removeItems: removeSavedSearches,
  updateItemStatus: updateSavedSearchStatus,
  updateItemsStatus: updateSavedSearchesStatus,
} = savedSearchesSlice.actions;

export default savedSearchesSlice.reducer;
