import { createListSlice } from "./createListSlice";

// Mock site visits linking a real listing (from listingsSlice / dashboard featured listings) to a
// real agent (from usersSlice) so the module reads as connected to the rest of the app, not an
// isolated island. Dates sit around "today" (2026-09-21) so the Upcoming/Today/Past grouping on
// the page has something meaningful to show for every bucket.
const initialItems = [
  {
    id: "VIS-40001",
    listingId: "lst-1",
    listingTitle: "Skyline Residency 3BHK",
    city: "Bandra West, Mumbai",
    buyerName: "Ananya Roy",
    buyerPhone: "+91 98111 22334",
    agentId: "USR-20065",
    agentName: "Vikram Desai",
    date: "2026-09-22",
    time: "11:00 AM",
    status: "confirmed",
    notes: "Buyer wants to check clubhouse and parking allocation.",
    createdDate: "2026-09-18",
  },
  {
    id: "VIS-40002",
    listingId: "PRP-10891",
    listingTitle: "Palm Meadows 4BHK Villa",
    city: "Whitefield, Bengaluru",
    buyerName: "Karan Malhotra",
    buyerPhone: "+91 98220 44556",
    agentId: "USR-20001",
    agentName: "Ravi Mehta",
    date: "2026-09-22",
    time: "4:30 PM",
    status: "requested",
    notes: "Requested a weekend slot originally; moved to Tuesday afternoon.",
    createdDate: "2026-09-19",
  },
  {
    id: "VIS-40003",
    listingId: "PRP-11540",
    listingTitle: "Office Space, Cyber Hub",
    city: "Cyber City, Gurugram",
    buyerName: "Meena Kapoor",
    buyerPhone: "+91 90210 55667",
    agentId: "USR-20047",
    agentName: "Cyberhub Developers Pvt Ltd",
    date: "2026-09-23",
    time: "2:00 PM",
    status: "confirmed",
    notes: "20-seat startup office lease — bring floor plan printouts.",
    createdDate: "2026-09-16",
  },
  {
    id: "VIS-40004",
    listingId: "lst-3",
    listingTitle: "Baner Heights Studio",
    city: "Baner, Pune",
    buyerName: "Vivek Rao",
    buyerPhone: "+91 90900 11223",
    agentId: "USR-20115",
    agentName: "Neha Kapoor",
    date: "2026-09-24",
    time: "10:30 AM",
    status: "requested",
    notes: "Wants to move in immediately if the unit checks out.",
    createdDate: "2026-09-20",
  },
  {
    id: "VIS-40005",
    listingId: "PRP-11207",
    listingTitle: "Residential Plot, Sector 88",
    city: "Sector 88, Gurugram",
    buyerName: "Suresh Iyer",
    buyerPhone: "+91 99887 11223",
    agentId: "USR-20033",
    agentName: "Ankit Shah",
    date: "2026-09-25",
    time: "9:00 AM",
    status: "rescheduled",
    notes: "Originally booked for 9/21 — buyer travelling, pushed by 4 days.",
    createdDate: "2026-09-14",
  },
  {
    id: "VIS-40006",
    listingId: "PRP-11902",
    listingTitle: "Zenith PG for Boys",
    city: "Hitech City, Hyderabad",
    buyerName: "Rohit Sharma",
    buyerPhone: "+91 88990 33445",
    agentId: "USR-20078",
    agentName: "Meridian Properties",
    date: "2026-09-26",
    time: "5:00 PM",
    status: "requested",
    notes: "",
    createdDate: "2026-09-21",
  },
  {
    id: "VIS-40007",
    listingId: "lst-2",
    listingTitle: "Whitefield Garden Villa",
    city: "Whitefield, Bengaluru",
    buyerName: "Divya Nair",
    buyerPhone: "+91 97700 88112",
    agentId: "USR-20001",
    agentName: "Ravi Mehta",
    date: "2026-09-19",
    time: "3:00 PM",
    status: "completed",
    notes: "Buyer confirmed sale deed is clear — moving to negotiation.",
    createdDate: "2026-09-10",
  },
  {
    id: "VIS-40008",
    listingId: "PRP-10234",
    listingTitle: "Spacious 2BHK Apartment in Prestige Tower 1",
    city: "Whitefield, Bengaluru",
    buyerName: "Priyanka Das",
    buyerPhone: "+91 98765 22110",
    agentId: "USR-20001",
    agentName: "Ravi Mehta",
    date: "2026-09-18",
    time: "1:00 PM",
    status: "completed",
    notes: "Asked follow-up on maintenance charges — sent via WhatsApp.",
    createdDate: "2026-09-12",
  },
  {
    id: "VIS-40009",
    listingId: "PRP-12034",
    listingTitle: "1BHK Flat, Kharadi",
    city: "Kharadi, Pune",
    buyerName: "Congratulations Winner",
    buyerPhone: "+91 00000 00000",
    agentId: "USR-20115",
    agentName: "Neha Kapoor",
    date: "2026-09-17",
    time: "11:00 AM",
    status: "cancelled",
    notes: "Lead flagged spam — visit cancelled.",
    createdDate: "2026-09-05",
  },
  {
    id: "VIS-40010",
    listingId: "PRP-12455",
    listingTitle: "Co-ed PG near Hitech City",
    city: "Hitech City, Hyderabad",
    buyerName: "Farhan Sheikh",
    buyerPhone: "+91 95050 66778",
    agentId: "USR-20078",
    agentName: "Meridian Properties",
    date: "2026-09-27",
    time: "6:00 PM",
    status: "confirmed",
    notes: "Wants to see single-sharing rooms specifically.",
    createdDate: "2026-09-20",
  },
  {
    id: "VIS-40011",
    listingId: "lst-4",
    listingTitle: "DLF Cyber Towers Office",
    city: "Cyber City, Gurugram",
    buyerName: "Aditya Verma",
    buyerPhone: "+91 96650 22114",
    agentId: "USR-20047",
    agentName: "Cyberhub Developers Pvt Ltd",
    date: "2026-09-15",
    time: "12:00 PM",
    status: "completed",
    notes: "Lease terms discussed on-site — draft agreement sent after.",
    createdDate: "2026-09-08",
  },
  {
    id: "VIS-40012",
    listingId: "PRP-12588",
    listingTitle: "Baner Heights Studio",
    city: "Baner, Pune",
    buyerName: "Sneha Joshi",
    buyerPhone: "+91 93330 99887",
    agentId: "USR-20140",
    agentName: "Deepak Verma",
    date: "2026-09-28",
    time: "10:00 AM",
    status: "requested",
    notes: "Wants interior + clubhouse photos before confirming the slot.",
    createdDate: "2026-09-21",
  },
];

const siteVisitsSlice = createListSlice("siteVisits", {
  items: initialItems,
  filters: { status: "all", agentId: "all" },
});

export const {
  setItems: setSiteVisits,
  setFilters: setSiteVisitsFilters,
  resetFilters: resetSiteVisitsFilters,
  setSelectedId: setSelectedSiteVisitId,
  setLoading: setSiteVisitsLoading,
  setError: setSiteVisitsError,
  addItem: addSiteVisit,
  updateItem: updateSiteVisit,
  removeItem: removeSiteVisit,
  removeItems: removeSiteVisits,
  updateItemStatus: updateSiteVisitStatus,
  updateItemsStatus: updateSiteVisitsStatus,
} = siteVisitsSlice.actions;

export default siteVisitsSlice.reducer;
