import { createListSlice } from "./createListSlice";

// Mock users covering every role the spec calls out (Buyer, Owner, Agent, Dealer, Builder) with
// KYC + RERA verification state for the roles that need it (Section 2.6 Agent/Broker features —
// RERA license + KYC approval flow) and account-moderation state (Section 4.3 — warn/suspend/ban).
const initialItems = [
  {
    id: "USR-20001",
    name: "Ravi Mehta",
    email: "ravi.mehta@example.com",
    phone: "+91 98765 43210",
    role: "Agent",
    city: "Bangalore",
    status: "active",
    joinedDate: "2025-11-02",
    lastActive: "2026-09-21",
    listingsCount: 14,
    warnings: [],
    verification: { kycStatus: "verified", reraStatus: "verified", reraNumber: "KA-RERA-12345", agencyName: "Mehta Realty" },
  },
  {
    id: "USR-20014",
    name: "Priya Desai",
    email: "priya.desai@example.com",
    phone: "+91 98220 11453",
    role: "Owner",
    city: "Mumbai",
    status: "active",
    joinedDate: "2026-01-15",
    lastActive: "2026-09-19",
    listingsCount: 3,
    warnings: [],
    verification: { kycStatus: "verified", reraStatus: "not_applicable", reraNumber: "", agencyName: "" },
  },
  {
    id: "USR-20033",
    name: "Ankit Shah",
    email: "ankit.shah@shahproperties.example.com",
    phone: "+91 99887 76655",
    role: "Dealer",
    city: "Gurugram",
    status: "active",
    joinedDate: "2025-08-20",
    lastActive: "2026-09-20",
    listingsCount: 22,
    warnings: [],
    verification: { kycStatus: "verified", reraStatus: "pending", reraNumber: "HR-RERA-55021", agencyName: "Shah Property Consultants" },
  },
  {
    id: "USR-20047",
    name: "Cyberhub Developers Pvt Ltd",
    email: "compliance@cyberhubdevelopers.example.com",
    phone: "+91 12442 90011",
    role: "Builder",
    city: "Gurugram",
    status: "active",
    joinedDate: "2025-05-10",
    lastActive: "2026-09-18",
    listingsCount: 8,
    warnings: [],
    verification: { kycStatus: "verified", reraStatus: "verified", reraNumber: "HR-RERA-99871", agencyName: "Cyberhub Developers Pvt Ltd" },
  },
  {
    id: "USR-20058",
    name: "Sunita Kulkarni",
    email: "sunita.kulkarni@example.com",
    phone: "+91 90210 33445",
    role: "Buyer",
    city: "Pune",
    status: "active",
    joinedDate: "2026-03-02",
    lastActive: "2026-09-17",
    listingsCount: 0,
    warnings: [],
    verification: { kycStatus: "not_required", reraStatus: "not_applicable", reraNumber: "", agencyName: "" },
  },
  {
    id: "USR-20065",
    name: "Vikram Desai",
    email: "vikram.desai@example.com",
    phone: "+91 98450 22110",
    role: "Agent",
    city: "Mumbai",
    status: "warned",
    joinedDate: "2025-09-18",
    lastActive: "2026-09-21",
    listingsCount: 19,
    warnings: [{ date: "2026-09-05", reason: "Misleading price mentioned in listing description — corrected after buyer complaint." }],
    verification: { kycStatus: "verified", reraStatus: "verified", reraNumber: "MH-RERA-44210", agencyName: "Desai Associates" },
  },
  {
    id: "USR-20078",
    name: "Meridian Properties",
    email: "admin@meridianproperties.example.com",
    phone: "+91 40 6655 8899",
    role: "Builder",
    city: "Hyderabad",
    status: "suspended",
    suspensionReason: "Uploaded a project brochure referencing a RERA registration that had already expired.",
    joinedDate: "2025-02-14",
    lastActive: "2026-09-10",
    listingsCount: 5,
    warnings: [{ date: "2026-08-02", reason: "First warning for outdated RERA documentation." }],
    verification: { kycStatus: "verified", reraStatus: "rejected", reraNumber: "TS-RERA-10982", agencyName: "Meridian Properties" },
  },
  {
    id: "USR-20089",
    name: "Arjun Nair",
    email: "arjun.nair@nairrealty.example.com",
    phone: "+91 94470 55123",
    role: "Agent",
    city: "Kochi",
    status: "active",
    joinedDate: "2026-06-01",
    lastActive: "2026-09-21",
    listingsCount: 2,
    warnings: [],
    verification: { kycStatus: "pending", reraStatus: "pending", reraNumber: "KL-RERA-77341", agencyName: "Nair Realty Associates" },
  },
  {
    id: "USR-20102",
    name: "Fake Deals Realty",
    email: "contact@fakedealsrealty.example.com",
    phone: "+91 98765 00000",
    role: "Dealer",
    city: "Delhi",
    status: "banned",
    banReason: "Multiple confirmed fraud reports from buyers; several listings found to be fake / non-existent properties.",
    joinedDate: "2025-04-22",
    lastActive: "2026-08-11",
    listingsCount: 0,
    warnings: [
      { date: "2026-06-01", reason: "Warned for duplicate listings across cities." },
      { date: "2026-07-14", reason: "Second warning — buyer reported no response after booking payment." },
    ],
    verification: { kycStatus: "rejected", reraStatus: "rejected", reraNumber: "DL-RERA-00219", agencyName: "Fake Deals Realty" },
  },
  {
    id: "USR-20115",
    name: "Neha Kapoor",
    email: "neha.kapoor@example.com",
    phone: "+91 88888 12121",
    role: "Owner",
    city: "Pune",
    status: "active",
    joinedDate: "2026-02-08",
    lastActive: "2026-09-15",
    listingsCount: 1,
    warnings: [],
    verification: { kycStatus: "verified", reraStatus: "not_applicable", reraNumber: "", agencyName: "" },
  },
  {
    id: "USR-20128",
    name: "Rajesh Kumar",
    email: "rajesh.kumar@example.com",
    phone: "+91 99110 44556",
    role: "Buyer",
    city: "Noida",
    status: "active",
    joinedDate: "2026-04-19",
    lastActive: "2026-09-20",
    listingsCount: 0,
    warnings: [],
    verification: { kycStatus: "not_required", reraStatus: "not_applicable", reraNumber: "", agencyName: "" },
  },
  {
    id: "USR-20140",
    name: "Deepak Verma",
    email: "deepak.verma@example.com",
    phone: "+91 90030 66778",
    role: "Agent",
    city: "Chennai",
    status: "warned",
    joinedDate: "2025-12-05",
    lastActive: "2026-09-19",
    listingsCount: 27,
    warnings: [{ date: "2026-09-12", reason: "Repeated duplicate listings flagged by moderation team." }],
    verification: { kycStatus: "verified", reraStatus: "verified", reraNumber: "TN-RERA-33012", agencyName: "Verma & Co. Estates" },
  },
];

const usersSlice = createListSlice("users", {
  items: initialItems,
  filters: { role: "all", status: "all" },
});

export const {
  setItems: setUsers,
  setFilters: setUsersFilters,
  resetFilters: resetUsersFilters,
  setSelectedId: setSelectedUserId,
  setLoading: setUsersLoading,
  setError: setUsersError,
  addItem: addUser,
  updateItem: updateUser,
  removeItem: removeUser,
  removeItems: removeUsers,
  updateItemStatus: updateUserStatus,
  updateItemsStatus: updateUsersStatus,
} = usersSlice.actions;

export default usersSlice.reducer;
